- name: install dependencies
  apt:
    name: 
     # make etc., necessary stuff for compiling 
      - build-essential
     # base dependencies 
      - libcairo2-dev
      - libjpeg-turbo8-dev
      - libpng-dev
      - libtool-bin
      - uuid-dev
      - libossp-uuid-dev
     # RDP dependencies 
      - freerdp2-dev
     # SSH dependencies
      - libpango1.0-dev
      - libssh2-1-dev
     # Ogg Vorbis dependencies
      - libvorbis-dev
     # WebP dependencies
      - libwebp-dev
     # OpenSSL dependencies
      - libssl-dev
     # FFmpeg (screen recording) dependencies
      - libswscale-dev
      - libavcodec-dev
      - libavutil-dev
      - libavformat-dev
     # prevent WebSocket connection error after install
      - libwebsockets-dev
     # used to download external archives
      - wget

- name: install Tomcat 9
  apt:
    name:
      - tomcat9
      - tomcat9-admin
      - tomcat9-common
      - tomcat9-user
    state: latest
  when: guacamole__tomcat_install == "yes"

- name: create Guacamole server temp dir
  file:
    state: directory
    path: /tmp/guacamole-server/

- name: download Guacamole server archive
  get_url:
    url: https://dlcdn.apache.org/guacamole/{{ guacamole__version }}/source/guacamole-server-{{ guacamole__version }}.tar.gz
    dest: /tmp/guacamole-server/

- name: extract Guacamole server archive
  unarchive:
    src: /tmp/guacamole-server/guacamole-server-{{ guacamole__version }}.tar.gz
    dest: /tmp/guacamole-server/
    remote_src: yes

- name: configure (ignore errors due to OpenSSL 3.0 on Ubuntu 22)
  shell: "CFLAGS=-Wno-error ./configure --with-systemd-dir=/etc/systemd/system/"
  args:
    chdir: /tmp/guacamole-server/guacamole-server-{{ guacamole__version }}/

- name: make 
  command: make
  args:
    chdir: /tmp/guacamole-server/guacamole-server-{{ guacamole__version }}/

- name: make install 
  command: make install
  args:
    chdir: /tmp/guacamole-server/guacamole-server-{{ guacamole__version }}/

- name: ldconfig
  command: ldconfig
  args:
    chdir: /tmp/guacamole-server

- name: download Guacamole server war
  get_url:
    url: https://dlcdn.apache.org/guacamole/{{ guacamole__version }}/binary/guacamole-{{ guacamole__version }}.war
    dest: /var/lib/tomcat9/webapps/guacamole.war

- name: download JDBC auth archive 
  get_url:
    url: https://dlcdn.apache.org/guacamole/{{ guacamole__version }}/binary/guacamole-auth-jdbc-{{ guacamole__version }}.tar.gz
    dest: /tmp/guacamole-server/
  when: guacamole__mysql_auth == 'yes'

- name: extract JDBC auth archive
  unarchive:
    src: /tmp/guacamole-server/guacamole-auth-jdbc-{{ guacamole__version }}.tar.gz
    dest: /tmp/guacamole-server/
    remote_src: yes
  when: guacamole__mysql_auth == 'yes'

- name: copy JDBC MySQL auth war to /etc/guacamole/extensions
  copy:
    src: /tmp/guacamole-server/guacamole-auth-jdbc-{{ guacamole__version }}/mysql/guacamole-auth-jdbc-mysql-{{ guacamole__version}}.jar
    dest: /etc/guacamole/extensions/
    remote_src: yes
  when: guacamole__mysql_auth == 'yes'

- name: create Guacamole database inside MySQL
  mysql_db:
    login_host: "{{ guacamole__mysql_host }}"
    login_user: "{{ guacamole__mysql_root_user }}"
    login_password: "{{ guacamole__mysql_root_password }}"
    name: "{{ guacamole__mysql_db }}"
    state: present
  when: guacamole__mysql_auth == 'yes'

- name: create Guacamole admin user inside MySQL
  mysql_user:
    login_host: "{{ guacamole__mysql_host }}"
    login_user: "{{ guacamole__mysql_root_user }}"
    login_password: "{{ guacamole__mysql_root_password }}"
    name: "{{ guacamole__mysql_user }}"
    host: "{{ guacamole__mysql_host }}"
    password: "{{ guacamole__mysql_password }}"
    priv: "{{ guacamole__mysql_db }}.*:SELECT,UPDATE,INSERT,DELETE"
  when: guacamole__mysql_auth == 'yes'

- name: import 001-create-schema.sql
  mysql_db:
    login_host: "{{ guacamole__mysql_host }}"
    login_user: "{{ guacamole__mysql_root_user }}"
    login_password: "{{ guacamole__mysql_root_password }}"
    name: "{{ guacamole__mysql_db }}"
    state: import
    target: /tmp/guacamole-server/guacamole-auth-jdbc-{{ guacamole__version }}/mysql/schema/001-create-schema.sql
  when: guacamole__mysql_auth == 'yes'

- name: import 002-create-admin-user.sql
  mysql_db:
    login_host: "{{ guacamole__mysql_host }}"
    login_user: "{{ guacamole__mysql_root_user }}"
    login_password: "{{ guacamole__mysql_root_password }}"
    name: "{{ guacamole__mysql_db }}"
    state: import
    target: /tmp/guacamole-server/guacamole-auth-jdbc-{{ guacamole__version }}/mysql/schema/002-create-admin-user.sql
  when: guacamole__mysql_auth == 'yes'

- name: download MySQL JDBC connector
  command: wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j-{{ guacamole__mysql_connector_java_ver }}.tar.gz
  args:
    chdir: /tmp/guacamole-server
  # the following is resulting in 403 errors as of Apr 2023
  #get_url:
  #  url: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j-{{ guacamole__mysql_connector_java_ver }}.tar.gz
  #  dest: /tmp/guacamole-server/
  when: guacamole__mysql_auth == 'yes'

- name: extract MySQL JDBC connector
  unarchive:
    src: /tmp/guacamole-server/mysql-connector-j-{{ guacamole__mysql_connector_java_ver }}.tar.gz
    dest: /tmp/guacamole-server/
    remote_src: yes
  when: guacamole__mysql_auth == 'yes'

- name: copy MySQL JDBC connector to /etc/guacamole/lib
  copy:
    src: /tmp/guacamole-server/mysql-connector-j-{{ guacamole__mysql_connector_java_ver }}/mysql-connector-j-{{ guacamole__mysql_connector_java_ver }}.jar
    dest: /etc/guacamole/lib/
    remote_src: yes
  when: guacamole__mysql_auth == 'yes'

- name: copy guacamole.properties (MySQL auth)
  template:
    src: guacamole.properties.mysql.j2
    dest: /etc/guacamole/guacamole.properties
    mode: '0644'
  when: guacamole__mysql_auth == 'yes'

- name: copy guacamole.properties (XML auth)
  template:
    src: guacamole.properties.xml.j2
    dest: /etc/guacamole/guacamole.properties
    mode: '0644'
  when: guacamole__mysql_auth != 'yes'

- name: copy user-mapping.xml (XML auth)
  template:
    src: user-mapping.j2
    dest: /etc/guacamole/user-mapping.xml
    mode: '0644'
  when: guacamole__mysql_auth != 'yes'

- name: download TOTP auth archive 
  get_url:
    url: https://dlcdn.apache.org/guacamole/{{ guacamole__version }}/binary/guacamole-auth-totp-{{ guacamole__version }}.tar.gz
    dest: /tmp/guacamole-server/
  when: guacamole__mysql_auth == 'yes' and guacamole__totp_auth == 'yes'

- name: extract TOTP auth archive
  unarchive:
    src: /tmp/guacamole-server/guacamole-auth-totp-{{ guacamole__version }}.tar.gz
    dest: /tmp/guacamole-server/
    remote_src: yes
  when: guacamole__mysql_auth == 'yes' and guacamole__totp_auth == 'yes'

- name: copy JDBC TOTP auth war to /etc/guacamole/extensions
  copy:
    src: /tmp/guacamole-server/guacamole-auth-totp-{{ guacamole__version }}/guacamole-auth-totp-{{ guacamole__version}}.jar
    dest: /etc/guacamole/extensions/
    remote_src: yes
  when: guacamole__mysql_auth == 'yes' and guacamole__totp_auth == 'yes'

- name: install xrdp
  apt:
    name: xrdp
  when: guacamole__xrdp_install == "yes"

- name: install LXQt desktop
  apt:
    name: lxqt-core
  when: guacamole__lxqt_install == "yes"

- name: restart Tomcat daemon
  systemd:
    name: tomcat9
    state: restarted

- name: restart Guacamole server daemon
  systemd:
    name: guacd
    state: restarted

- name: delete temp dir
  file:
    state: absent
    path: /tmp/guacamole-server/

